### ISSUE TITLE
export.mayu:  AttributeError: 'list' object has no attribute 'mayu_cutoff'

### ISSUE THREAD

**Issue by danielhyduke** [uweschmitt/pyprophet#18]
When running pyprophet 0.18.3 with the --export.mayu flag, I get the following error:

AttributeError: 'list' object has no attribute 'mayu_cutoff'

The exception appears to be from the codeblock below which worked in pyprophet 0.13.3 because out_pathes was a Pathes object with these listed attributes; however, in the 0.18.3 version out_pathes is now a list that contains a dictionary where the keys are the attributes.

https://github.com/uweschmitt/pyprophet/blob/master/pyprophet/main.py#L203
```python
    export_mayu(out_pathes.mayu_cutoff, out_pathes.mayu_fasta,
             out_pathes.mayu_csv, scored_table, result.final_statistics)
    print "WRITTEN: ", out_pathes.mayu_cutoff
    print "WRITTEN: ", out_pathes.mayu_fasta
    print "WRITTEN: ", out_pathes.mayu_csv
```

pyprophet 0.18.3 
OpenSwathWorkflow -- Complete workflow to run OpenSWATH
Version: 2.0.0 Sep 9 2015, 13:29:57, Revision: 66a7739
CENTOS 7 64-bit
python 2.7.9
